site_name: AI Driver Note
site_description: Notes on assisting software development through AI, written using the MkDocs framework
site_author: Dyson Liu
repo_url: https://github.com/microsystex/ai-driver-note

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top

nav:
  - Home: index.md
  - Azure OpenAI:
    - Azure OpenAI: azure-openai/azure-openai.md
  - CLI Tools: 
    - Python venv Guide: cli-tools/python-venv.md
    - CLI Tools with Python: cli-tools/cli-with-python.md
  - Azure DevOps:
    - Pipeline Permissions: azure-devops/pipeline-permission.md
    - CLI Deployment: azure-devops/cli-artifacts.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - def_list  